name: DokiDoki
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI & utils
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3

  # Networking & images
  dio: ^5.9.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2

  # (Opsional) Storage lokal — kamu boleh hapus kalau tidak dipakai
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # (Opsional) Localization bawaan Flutter — aman dibiarkan meski tak dipakai
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  # Tidak perlu menambahkan ikon ke assets di sini; generator membaca langsung dari path di bawah.

# ====== Flutter Launcher Icons Config ======
# Siapkan file:
# - assets/icons/app_icon.png                  (untuk iOS; 1024x1024, PNG, tanpa rounded)
# - assets/icons/app_icon_foreground.png       (untuk Android Adaptive; 1024x1024, logo/mark)
# (opsional) assets/icons/app_icon_background.png  -> jika tidak pakai warna heksadesimal
flutter_launcher_icons:
  android: true
  image_path_ios: assets/icons/app_icon.png
  adaptive_icon_foreground: assets/icons/app_icon.png
  min_sdk_android: 21
